name: Footprint test

on:
  push:
   # TODO REMOVE \/
    branches: [ '*', 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  footprint_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Get the arm-non-eabi-gcc toolchain
      - name: Install arm-none-eabi-gcc
        run : |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: make clean
        run: |
          make keysclean && rm -f include/target.h

      - name: Install wolfSSL
        run: |
          sudo apt-get install --no-install-recommends -y -q make libwolfssl-dev

      - name: Select config
        run: |
          cp config/examples/stm32f407-discovery.config .config && make include/target.h

      - name: Build key tools
        run: |
          make keytools

      - name: Build wolfboot and test footprint
        run: |
          make test-size-all

