name: Unit tests

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: install libcheck
        run: sudo apt-get install --no-install-recommends -y -q check

      - name: make clean
        run: |
          make keysclean && make -C tools/keytools clean && rm -f include/target.h

      - name: Build unit tests
        run: |
          make -C tools/unit-tests

      - name: Run unit tests
        run: |
          make -C tools/unit-tests run
