name: Renode Automated multi SHA algorithms

on:
  push:
    # TODO REMOVE \/
    branches: [  '*', 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  renode_automated_multi_sha:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Select config
        run: |
          cp config/examples/nrf52840.config .config && make include/target.h

##### SHA-3 tests
# SIGN=NONE TEST
      - name: Renode Tests SIGN=NONE HASH=SHA3
        run: ./tools/renode/docker-test.sh "SIGN=NONE HASH=SHA3"


# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 HASH=SHA3"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 HASH=SHA3"

# ECC521 TEST
      - name: Renode Tests ECC521
        run: ./tools/renode/docker-test.sh "SIGN=ECC521 HASH=SHA3"

# ED25519 TEST
      - name: Renode Tests ED25519
        run: ./tools/renode/docker-test.sh "SIGN=ED25519 HASH=SHA3"


# ED448 TEST
      - name: Renode Tests ED448
        run: ./tools/renode/docker-test.sh "SIGN=ED448 HASH=SHA3"


# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 HASH=SHA3"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 HASH=SHA3"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 HASH=SHA3"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v4
        with:
          name: Renode Test Results
          path: test_results/
